### ISSUE TITLE
oci-image-tool failed to unpack

### ISSUE THREAD

**Issue by jovizhangwei** [opencontainers/image-tools#188] opened 2017-10-12 07:50 UTC
```
[xianwei.zw@buffer010101170038.et2sqa /home/xianwei.zw/gocode/src/github.com/opencontainers/test]
$sudo docker save nginx:alpine | docker2oci nginx

[xianwei.zw@buffer010101170038.et2sqa /home/xianwei.zw/gocode/src/github.com/opencontainers/test]
$tree nginx
nginx
├── blobs
│   └── sha256
│       ├── 040fd7841192c4f283485d5c7817f4508a774a8fabef8fc265c87f4d2a2ae635
│       ├── 9d93ce18f76eb7e55938bc943541010a83227ff6081fa39a168b4c9a21bfed03
│       ├── be269c61895ec0869f6ce83c4fcf22f5b343cfe1c31d69959a6e49af17329b56
│       ├── c0326cfaf747aa2703fa448edf24f9638ba7e6b36dda7f7a97a53039b5a8c83b
│       ├── de88aa7ce14e79addca455533ec2c8e0ecce7153077b7c0312e834728e90e182
│       └── e84831b3be3298529fffc9c4b19aa83ee080906d614923ac6d2e6e688913e4ea
├── index.json
└── oci-layout

2 directories, 8 files

[xianwei.zw@buffer010101170038.et2sqa /home/xianwei.zw/gocode/src/github.com/opencontainers/test]
$oci-image-tool create --ref alpine nginx bundle/
symlink /bin/busybox bundle/rootfs/usr/bin/strings: file exists
error unpack: extracting layer
github.com/opencontainers/image-tools/image.(*manifest).unpack.func2
	/home/xianwei.zw/gocode/src/github.com/opencontainers/image-tools/image/manifest.go:127
github.com/opencontainers/image-tools/image.(*pathWalker).walk.func1
	/home/xianwei.zw/gocode/src/github.com/opencontainers/image-tools/image/walker.go:162
path/filepath.walk
	/home/xianwei.zw/go/src/path/filepath/path.go:351
path/filepath.walk
	/home/xianwei.zw/go/src/path/filepath/path.go:376
path/filepath.walk
	/home/xianwei.zw/go/src/path/filepath/path.go:376
path/filepath.walk
	/home/xianwei.zw/go/src/path/filepath/path.go:376
path/filepath.Walk
	/home/xianwei.zw/go/src/path/filepath/path.go:398
github.com/opencontainers/image-tools/image.(*pathWalker).walk
	/home/xianwei.zw/gocode/src/github.com/opencontainers/image-tools/image/walker.go:163
github.com/opencontainers/image-tools/image.(*manifest).unpack
	/home/xianwei.zw/gocode/src/github.com/opencontainers/image-tools/image/manifest.go:131
github.com/opencontainers/image-tools/image.createBundle
	/home/xianwei.zw/gocode/src/github.com/opencontainers/image-tools/image/image.go:337
github.com/opencontainers/image-tools/image.createRuntimeBundle
	/home/xianwei.zw/gocode/src/github.com/opencontainers/image-tools/image/image.go:288
github.com/opencontainers/image-tools/image.CreateRuntimeBundleLayout
	/home/xianwei.zw/gocode/src/github.com/opencontainers/image-tools/image/image.go:235
main.createHandle
	/home/xianwei.zw/gocode/src/github.com/opencontainers/image-tools/cmd/oci-image-tool/create.go:62
github.com/opencontainers/image-tools/vendor/github.com/urfave/cli.HandleAction
	/home/xianwei.zw/gocode/src/github.com/opencontainers/image-tools/vendor/github.com/urfave/cli/app.go:485
github.com/opencontainers/image-tools/vendor/github.com/urfave/cli.Command.Run
	/home/xianwei.zw/gocode/src/github.com/opencontainers/image-tools/vendor/github.com/urfave/cli/command.go:193
github.com/opencontainers/image-tools/vendor/github.com/urfave/cli.(*App).Run
	/home/xianwei.zw/gocode/src/github.com/opencontainers/image-tools/vendor/github.com/urfave/cli/app.go:250
main.main
	/home/xianwei.zw/gocode/src/github.com/opencontainers/image-tools/cmd/oci-image-tool/main.go:57
runtime.main
	/home/xianwei.zw/go/src/runtime/proc.go:185
runtime.goexit
	/home/xianwei.zw/go/src/runtime/asm_amd64.s:2197
```

**Comment by cyphar** [comment] 2017-10-12 07:54
I believe this is caused by us not removing an existing file if the type has changed on extraction.

As an aside, if you'd like to take a look at another tool for manipulating OCI images, I'd recommend [umoci](https://github.com/openSUSE/umoci) (which is a tool I wrote and we use quite heavily at SUSE).

**Comment by coolljt0725** [comment] 2017-10-12 07:57
same issue https://github.com/opencontainers/image-tools/issues/41 and may fixed by https://github.com/opencontainers/image-tools/pull/42?

**Comment by jovizhangwei** [comment] 2017-10-12 08:07
umoci is also not working.

```
$sudo docker save nginx:alpine | docker2oci nginx

[xianwei.zw@buffer010101170038.et2sqa /home/xianwei.zw/gocode/src/github.com/opencontainers/test]
$umoci unpack --image nginx:alpine rootfs
   ⨯ create runtime bundle: chown rootfs: lchown rootfs/rootfs: operation not permitted

[xianwei.zw@buffer010101170038.et2sqa /home/xianwei.zw/gocode/src/github.com/opencontainers/test]
$sudo umoci unpack --image nginx:alpine rootfs
   ⨯ create runtime bundle: create gzip reader: gzip: invalid header
```

**Comment by q384566678** [comment] 2017-10-12 08:25
I can do that in #42 . @coolljt0725 Shell we merge #42  to solve this problem?

**Comment by jovizhangwei** [comment] 2017-10-12 08:30
@q384566678  I got this after merged #42 locally.

```
$ls nginx
blobs  index.json  oci-layout

$oci-create-runtime-bundle nginx bundle
unpacking failed: refs/v1.0: descriptor not found
```

**Comment by q384566678** [comment] 2017-10-12 08:34
After you merged this, you need to `git rebase` first, and then `make tool`.

**Comment by jovizhangwei** [comment] 2017-10-12 08:44
Oh, it works, #42 indeed fixed my problem. Thanks guys. @coolljt0725 @q384566678 @cyphar

**Closed** 2017-10-12 08:54 UTC
